# Generated by Django 5.2.7 on 2025-10-31 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('endereco', models.CharField(blank=True, default='', max_length=180)),
                ('numero', models.CharField(blank=True, default='', max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=120)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
