# Generated by Django 5.2.8 on 2025-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_colors_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
