# Generated by Django 5.2.8 on 2025-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_category_options_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group_title',
            field=models.CharField(max_length=60, blank=True, default=''),
        ),
    ]